services:
  - type: web
    name: voanh-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
        sync: false
