services:
  - type: web
    name: voanh-backend-v1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NOTION_API_KEY
        value: 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
      - key: NOTION_DATABASE_ID
        value: 231438efbf1c80a6b018f6347fc20726
      - key: PORT
        value: 3000
